name: Build LaTeX PDFs

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build PDFs
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: tex
          root_file: |
            main_eng.tex
            main_ita.tex
          args: -interaction=nonstopmode

      - name: Move PDFs
        run: |
          mkdir -p pdf
          mv tex/*.pdf pdf/

      - name: Commit PDFs
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add pdf/*.pdf
          git diff --cached --quiet || git commit -m "Update generated PDFs"
          git push
